CREATE TABLE public.needs_offers_compatibility (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  need_value text NOT NULL CHECK (btrim(need_value) <> ''),
  offer_value text NOT NULL CHECK (btrim(offer_value) <> ''),
  match_weight numeric(2, 1) NOT NULL CHECK (match_weight IN (0.7, 1.0)),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX needs_offers_compatibility_pair_key
  ON public.needs_offers_compatibility (lower(need_value), lower(offer_value));

ALTER TABLE public.needs_offers_compatibility ENABLE ROW LEVEL SECURITY;

-- Exact matches are intentionally handled by case-insensitive string equality
-- in the scorer. This table stores the approved conceptual/near matches only.
INSERT INTO public.needs_offers_compatibility (need_value, offer_value, match_weight)
VALUES
  ('Finding Customers', 'Customer Introductions', 0.7),
  ('Finding Customers', 'Sales Expertise', 0.7),
  ('Finding Customers', 'Business Development Expertise', 0.7),
  ('Raising Capital', 'Investment Capital', 0.7),
  ('Raising Capital', 'Fundraising Advice', 0.7),
  ('Hiring Talent', 'Hiring Opportunities', 0.7),
  ('Hiring Talent', 'Talent Referrals', 0.7),
  ('Finding a New Role', 'Hiring Opportunities', 0.7),
  ('Finding a New Role', 'Career Advice', 0.7),
  ('Career Growth', 'Career Advice', 0.7),
  ('Career Growth', 'Mentorship', 0.7),
  ('Career Growth', 'Founder Advice', 0.7),
  ('Building Partnerships', 'Partnership Introductions', 0.7),
  ('Building Partnerships', 'Business Development Expertise', 0.7),
  ('Finding Brand Partners', 'Brand Opportunities', 0.7),
  ('Finding Brand Partners', 'Brand Expertise', 0.7),
  ('Brand Strategy', 'Brand Expertise', 0.7),
  ('Marketing', 'Marketing Expertise', 0.7),
  ('Sales / Business Development', 'Sales Expertise', 0.7),
  ('Sales / Business Development', 'Business Development Expertise', 0.7),
  ('Product Development', 'Product Expertise', 0.7),
  ('Technology / Engineering', 'Technical Expertise', 0.7),
  ('Technology / Engineering', 'Engineering Expertise', 0.7),
  ('Operations', 'Operations Expertise', 0.7),
  ('Recruiting', 'Hiring Opportunities', 0.7),
  ('Recruiting', 'Talent Referrals', 0.7),
  ('Fundraising Strategy', 'Fundraising Advice', 0.7),
  ('Fundraising Strategy', 'Investment Capital', 0.7),
  ('Social Media', 'Social Media Expertise', 0.7),
  ('Design', 'Design Expertise', 0.7),
  ('Data / Analytics', 'Data / Analytics Expertise', 0.7),
  ('Entering a New Industry', 'Industry Knowledge', 0.7),
  ('Entering a New Market', 'Industry Knowledge', 0.7),
  ('Entering a New Market', 'Strategic Advice', 0.7),
  ('Meeting People Locally', 'Local City Knowledge', 0.7),
  ('Meeting People Locally', 'Community Connections', 0.7);
